---
- name: Deploy Task Management GraphQL API
  hosts: localhost
  become: yes

  tasks:
    - name: Ensure Node.js and npm are installed
      apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: yes

    - name: Copy project files to WSL home directory (excluding node_modules)
      synchronize:
        src: /mnt/d/Projects/FOSS_exp5/
        dest: /home/kishore/taskapi/
        rsync_opts:
          - "--exclude=node_modules"
          - "--exclude=.git"

    - name: Install project dependencies
      shell: |
        cd /home/kishore/taskapi
        npm install

    - name: Start the GraphQL server
      shell: |
        cd /home/kishore/taskapi
        nohup npm start &
