---
- name: Deploy Task Management GraphQL API
  hosts: local
  tasks:
    - name: Ensure Node.js and npm are installed
      apt:
        name: ["nodejs", "npm"]
        state: present
      become: yes

    - name: Copy project files to WSL home directory
      copy:
        src: /mnt/d/Projects/FOSS_exp5/
        dest: /home/{{ lookup('env','USER') }}/taskapi/
        mode: 0755
      

    - name: Install npm dependencies
      command: npm install
      args:
        chdir: /home/{{ lookup('env','USER') }}/taskapi

    - name: Start the Node.js server
      command: npm start
      args:
        chdir: /home/{{ lookup('env','USER') }}/taskapi
      async: 45
      poll: 0

    - name: Confirm deployment
      debug:
        msg: "GraphQL Task API deployed and running on http://localhost:4000/graphql"
